// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Account {
  final String id;
  final String name;
  final String avatar;
  final Map<String, String> cookies;
  final AuthTokens authTokens;
  final bool isLoggedIn;

  const Account({
    required this.id,
    required this.name,
    required this.avatar,
    required this.cookies,
    required this.authTokens,
    required this.isLoggedIn,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      avatar.hashCode ^
      cookies.hashCode ^
      authTokens.hashCode ^
      isLoggedIn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Account &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatar == other.avatar &&
          cookies == other.cookies &&
          authTokens == other.authTokens &&
          isLoggedIn == other.isLoggedIn;
}

class AuthTokens {
  final String? accessToken;
  final String? refreshToken;
  final PlatformInt64? expiresAt;

  const AuthTokens({
    this.accessToken,
    this.refreshToken,
    this.expiresAt,
  });

  @override
  int get hashCode =>
      accessToken.hashCode ^ refreshToken.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthTokens &&
          runtimeType == other.runtimeType &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          expiresAt == other.expiresAt;
}
