// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/models/common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Comment {
  final PlatformInt64 id;
  final PlatformInt64 oid;
  final PlatformInt64 uid;
  final String username;
  final Image avatar;
  final String content;
  final BigInt likeCount;
  final BigInt replyCount;
  final PlatformInt64 publishTime;
  final List<Comment> replies;

  const Comment({
    required this.id,
    required this.oid,
    required this.uid,
    required this.username,
    required this.avatar,
    required this.content,
    required this.likeCount,
    required this.replyCount,
    required this.publishTime,
    required this.replies,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      oid.hashCode ^
      uid.hashCode ^
      username.hashCode ^
      avatar.hashCode ^
      content.hashCode ^
      likeCount.hashCode ^
      replyCount.hashCode ^
      publishTime.hashCode ^
      replies.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Comment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          oid == other.oid &&
          uid == other.uid &&
          username == other.username &&
          avatar == other.avatar &&
          content == other.content &&
          likeCount == other.likeCount &&
          replyCount == other.replyCount &&
          publishTime == other.publishTime &&
          replies == other.replies;
}

class CommentList {
  final List<Comment> comments;
  final int page;
  final int pageSize;
  final int totalCount;

  const CommentList({
    required this.comments,
    required this.page,
    required this.pageSize,
    required this.totalCount,
  });

  @override
  int get hashCode =>
      comments.hashCode ^
      page.hashCode ^
      pageSize.hashCode ^
      totalCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentList &&
          runtimeType == other.runtimeType &&
          comments == other.comments &&
          page == other.page &&
          pageSize == other.pageSize &&
          totalCount == other.totalCount;
}
