// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:PiliPlus/src/rust/models/video.dart';
part 'download.freezed.dart';

@freezed
sealed class DownloadStatusData with _$DownloadStatusData {
  const DownloadStatusData._();

  const factory DownloadStatusData.pending() = DownloadStatusData_Pending;
  const factory DownloadStatusData.downloading({
    required double speed,
    double? eta,
  }) = DownloadStatusData_Downloading;
  const factory DownloadStatusData.paused() = DownloadStatusData_Paused;
  const factory DownloadStatusData.completed() = DownloadStatusData_Completed;
  const factory DownloadStatusData.failed({
    required String error,
  }) = DownloadStatusData_Failed;
  const factory DownloadStatusData.cancelled() = DownloadStatusData_Cancelled;
}

/// Download task representation for bridge compatibility
class DownloadTaskData {
  final String id;
  final String videoId;
  final String title;
  final VideoQuality quality;
  final BigInt totalBytes;
  final BigInt downloadedBytes;
  final DownloadStatusData status;
  final String filePath;
  final bool canResume;
  final PlatformInt64 createdAt;
  final PlatformInt64? completedAt;

  const DownloadTaskData({
    required this.id,
    required this.videoId,
    required this.title,
    required this.quality,
    required this.totalBytes,
    required this.downloadedBytes,
    required this.status,
    required this.filePath,
    required this.canResume,
    required this.createdAt,
    this.completedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      videoId.hashCode ^
      title.hashCode ^
      quality.hashCode ^
      totalBytes.hashCode ^
      downloadedBytes.hashCode ^
      status.hashCode ^
      filePath.hashCode ^
      canResume.hashCode ^
      createdAt.hashCode ^
      completedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadTaskData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          videoId == other.videoId &&
          title == other.title &&
          quality == other.quality &&
          totalBytes == other.totalBytes &&
          downloadedBytes == other.downloadedBytes &&
          status == other.status &&
          filePath == other.filePath &&
          canResume == other.canResume &&
          createdAt == other.createdAt &&
          completedAt == other.completedAt;
}
