// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/models/common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class LivePlayUrl {
  final LiveQuality quality;
  final List<String> urls;

  const LivePlayUrl({
    required this.quality,
    required this.urls,
  });

  @override
  int get hashCode => quality.hashCode ^ urls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LivePlayUrl &&
          runtimeType == other.runtimeType &&
          quality == other.quality &&
          urls == other.urls;
}

enum LiveQuality {
  low,
  medium,
  high,
  ultra,
}

class LiveRoomInfo {
  final PlatformInt64 roomId;
  final PlatformInt64 uid;
  final String title;
  final String description;
  final Image cover;
  final LiveStatus status;
  final BigInt onlineCount;
  final String areaName;

  const LiveRoomInfo({
    required this.roomId,
    required this.uid,
    required this.title,
    required this.description,
    required this.cover,
    required this.status,
    required this.onlineCount,
    required this.areaName,
  });

  @override
  int get hashCode =>
      roomId.hashCode ^
      uid.hashCode ^
      title.hashCode ^
      description.hashCode ^
      cover.hashCode ^
      status.hashCode ^
      onlineCount.hashCode ^
      areaName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiveRoomInfo &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          uid == other.uid &&
          title == other.title &&
          description == other.description &&
          cover == other.cover &&
          status == other.status &&
          onlineCount == other.onlineCount &&
          areaName == other.areaName;
}

enum LiveStatus {
  live,
  preview,
  round,
}
