// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RcmdOwner {
  final PlatformInt64 mid;
  final String name;
  final String? face;

  const RcmdOwner({
    required this.mid,
    required this.name,
    this.face,
  });

  @override
  int get hashCode => mid.hashCode ^ name.hashCode ^ face.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RcmdOwner &&
          runtimeType == other.runtimeType &&
          mid == other.mid &&
          name == other.name &&
          face == other.face;
}

class RcmdStat {
  final PlatformInt64? view;
  final PlatformInt64? like;
  final PlatformInt64? danmaku;

  const RcmdStat({
    this.view,
    this.like,
    this.danmaku,
  });

  @override
  int get hashCode => view.hashCode ^ like.hashCode ^ danmaku.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RcmdStat &&
          runtimeType == other.runtimeType &&
          view == other.view &&
          like == other.like &&
          danmaku == other.danmaku;
}

class RcmdVideoInfo {
  final PlatformInt64? id;
  final String bvid;
  final PlatformInt64? cid;
  final String? goto;
  final String? uri;
  final String? pic;
  final String title;
  final int duration;
  final PlatformInt64? pubdate;
  final RcmdOwner owner;
  final RcmdStat stat;
  final bool isFollowed;
  final String? rcmdReason;

  const RcmdVideoInfo({
    this.id,
    required this.bvid,
    this.cid,
    this.goto,
    this.uri,
    this.pic,
    required this.title,
    required this.duration,
    this.pubdate,
    required this.owner,
    required this.stat,
    required this.isFollowed,
    this.rcmdReason,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      bvid.hashCode ^
      cid.hashCode ^
      goto.hashCode ^
      uri.hashCode ^
      pic.hashCode ^
      title.hashCode ^
      duration.hashCode ^
      pubdate.hashCode ^
      owner.hashCode ^
      stat.hashCode ^
      isFollowed.hashCode ^
      rcmdReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RcmdVideoInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          bvid == other.bvid &&
          cid == other.cid &&
          goto == other.goto &&
          uri == other.uri &&
          pic == other.pic &&
          title == other.title &&
          duration == other.duration &&
          pubdate == other.pubdate &&
          owner == other.owner &&
          stat == other.stat &&
          isFollowed == other.isFollowed &&
          rcmdReason == other.rcmdReason;
}
