// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Search result for a single video
class SearchVideoItem {
  final String bvid;
  final PlatformInt64 aid;
  final String title;
  final String description;
  final String cover;
  final int duration;
  final PlatformInt64 pubdate;
  final PlatformInt64 ctime;
  final SearchVideoOwner owner;
  final SearchVideoStat stat;
  final int isUnionVideo;
  final String? type;
  final String? tag;

  const SearchVideoItem({
    required this.bvid,
    required this.aid,
    required this.title,
    required this.description,
    required this.cover,
    required this.duration,
    required this.pubdate,
    required this.ctime,
    required this.owner,
    required this.stat,
    required this.isUnionVideo,
    this.type,
    this.tag,
  });

  @override
  int get hashCode =>
      bvid.hashCode ^
      aid.hashCode ^
      title.hashCode ^
      description.hashCode ^
      cover.hashCode ^
      duration.hashCode ^
      pubdate.hashCode ^
      ctime.hashCode ^
      owner.hashCode ^
      stat.hashCode ^
      isUnionVideo.hashCode ^
      type.hashCode ^
      tag.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchVideoItem &&
          runtimeType == other.runtimeType &&
          bvid == other.bvid &&
          aid == other.aid &&
          title == other.title &&
          description == other.description &&
          cover == other.cover &&
          duration == other.duration &&
          pubdate == other.pubdate &&
          ctime == other.ctime &&
          owner == other.owner &&
          stat == other.stat &&
          isUnionVideo == other.isUnionVideo &&
          type == other.type &&
          tag == other.tag;
}

/// Owner information for search result
class SearchVideoOwner {
  final PlatformInt64 mid;
  final String name;
  final String face;

  const SearchVideoOwner({
    required this.mid,
    required this.name,
    required this.face,
  });

  @override
  int get hashCode => mid.hashCode ^ name.hashCode ^ face.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchVideoOwner &&
          runtimeType == other.runtimeType &&
          mid == other.mid &&
          name == other.name &&
          face == other.face;
}

/// Complete search results response
class SearchVideoResult {
  final List<SearchVideoItem> items;
  final int page;
  final int pageSize;
  final int numResults;

  const SearchVideoResult({
    required this.items,
    required this.page,
    required this.pageSize,
    required this.numResults,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ pageSize.hashCode ^ numResults.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchVideoResult &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          numResults == other.numResults;
}

/// Statistics for search result
class SearchVideoStat {
  final PlatformInt64 view;
  final PlatformInt64 like;
  final PlatformInt64 danmaku;

  const SearchVideoStat({
    required this.view,
    required this.like,
    required this.danmaku,
  });

  @override
  int get hashCode => view.hashCode ^ like.hashCode ^ danmaku.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchVideoStat &&
          runtimeType == other.runtimeType &&
          view == other.view &&
          like == other.like &&
          danmaku == other.danmaku;
}
