// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/models/common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class CoinBalance {
  final int coins;

  const CoinBalance({
    required this.coins,
  });

  @override
  int get hashCode => coins.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoinBalance &&
          runtimeType == other.runtimeType &&
          coins == other.coins;
}

class UserInfo {
  final PlatformInt64 mid;
  final String name;
  final Image face;
  final UserLevel levelInfo;
  final VipStatus vipStatus;
  final CoinBalance money;

  const UserInfo({
    required this.mid,
    required this.name,
    required this.face,
    required this.levelInfo,
    required this.vipStatus,
    required this.money,
  });

  @override
  int get hashCode =>
      mid.hashCode ^
      name.hashCode ^
      face.hashCode ^
      levelInfo.hashCode ^
      vipStatus.hashCode ^
      money.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserInfo &&
          runtimeType == other.runtimeType &&
          mid == other.mid &&
          name == other.name &&
          face == other.face &&
          levelInfo == other.levelInfo &&
          vipStatus == other.vipStatus &&
          money == other.money;
}

class UserLevel {
  final int currentLevel;

  const UserLevel({
    required this.currentLevel,
  });

  @override
  int get hashCode => currentLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserLevel &&
          runtimeType == other.runtimeType &&
          currentLevel == other.currentLevel;
}

class UserStats {
  final int following;
  final int follower;

  const UserStats({
    required this.following,
    required this.follower,
  });

  @override
  int get hashCode => following.hashCode ^ follower.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserStats &&
          runtimeType == other.runtimeType &&
          following == other.following &&
          follower == other.follower;
}

class VipStatus {
  final int status;
  final int vipType;

  const VipStatus({
    required this.status,
    required this.vipType,
  });

  @override
  int get hashCode => status.hashCode ^ vipType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VipStatus &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          vipType == other.vipType;
}
