// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// User information matching Bilibili API response
class UserInfo {
  final PlatformInt64 mid;
  final String name;
  final String face;
  final UserLevel levelInfo;
  final VipStatus vipStatus;
  final double money;
  final int emailVerified;
  final int mobileVerified;
  final int moral;
  final int scores;
  final PlatformInt64 vipDueDate;
  final int vipPayType;
  final int vipThemeType;
  final int vipAvatarSub;
  final String vipNicknameColor;
  final bool hasShop;
  final String shopUrl;
  final int isSeniorMember;

  const UserInfo({
    required this.mid,
    required this.name,
    required this.face,
    required this.levelInfo,
    required this.vipStatus,
    required this.money,
    required this.emailVerified,
    required this.mobileVerified,
    required this.moral,
    required this.scores,
    required this.vipDueDate,
    required this.vipPayType,
    required this.vipThemeType,
    required this.vipAvatarSub,
    required this.vipNicknameColor,
    required this.hasShop,
    required this.shopUrl,
    required this.isSeniorMember,
  });

  @override
  int get hashCode =>
      mid.hashCode ^
      name.hashCode ^
      face.hashCode ^
      levelInfo.hashCode ^
      vipStatus.hashCode ^
      money.hashCode ^
      emailVerified.hashCode ^
      mobileVerified.hashCode ^
      moral.hashCode ^
      scores.hashCode ^
      vipDueDate.hashCode ^
      vipPayType.hashCode ^
      vipThemeType.hashCode ^
      vipAvatarSub.hashCode ^
      vipNicknameColor.hashCode ^
      hasShop.hashCode ^
      shopUrl.hashCode ^
      isSeniorMember.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserInfo &&
          runtimeType == other.runtimeType &&
          mid == other.mid &&
          name == other.name &&
          face == other.face &&
          levelInfo == other.levelInfo &&
          vipStatus == other.vipStatus &&
          money == other.money &&
          emailVerified == other.emailVerified &&
          mobileVerified == other.mobileVerified &&
          moral == other.moral &&
          scores == other.scores &&
          vipDueDate == other.vipDueDate &&
          vipPayType == other.vipPayType &&
          vipThemeType == other.vipThemeType &&
          vipAvatarSub == other.vipAvatarSub &&
          vipNicknameColor == other.vipNicknameColor &&
          hasShop == other.hasShop &&
          shopUrl == other.shopUrl &&
          isSeniorMember == other.isSeniorMember;
}

class UserLevel {
  final int currentLevel;
  final int currentMin;
  final int currentExp;
  final int nextExp;

  const UserLevel({
    required this.currentLevel,
    required this.currentMin,
    required this.currentExp,
    required this.nextExp,
  });

  @override
  int get hashCode =>
      currentLevel.hashCode ^
      currentMin.hashCode ^
      currentExp.hashCode ^
      nextExp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserLevel &&
          runtimeType == other.runtimeType &&
          currentLevel == other.currentLevel &&
          currentMin == other.currentMin &&
          currentExp == other.currentExp &&
          nextExp == other.nextExp;
}

class UserStats {
  final int following;
  final int follower;
  final int dynamicCount;

  const UserStats({
    required this.following,
    required this.follower,
    required this.dynamicCount,
  });

  @override
  int get hashCode =>
      following.hashCode ^ follower.hashCode ^ dynamicCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserStats &&
          runtimeType == other.runtimeType &&
          following == other.following &&
          follower == other.follower &&
          dynamicCount == other.dynamicCount;
}

class VipStatus {
  final int status;
  final int vipType;

  const VipStatus({
    required this.status,
    required this.vipType,
  });

  @override
  int get hashCode => status.hashCode ^ vipType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VipStatus &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          vipType == other.vipType;
}
