// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/models/common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum VideoFormat {
  mp4,
  dash,
}

class VideoInfo {
  final String bvid;
  final PlatformInt64 aid;
  final String title;
  final String description;
  final VideoOwner owner;
  final Image pic;
  final int duration;
  final VideoStats stats;
  final PlatformInt64 cid;
  final List<VideoPage> pages;

  const VideoInfo({
    required this.bvid,
    required this.aid,
    required this.title,
    required this.description,
    required this.owner,
    required this.pic,
    required this.duration,
    required this.stats,
    required this.cid,
    required this.pages,
  });

  @override
  int get hashCode =>
      bvid.hashCode ^
      aid.hashCode ^
      title.hashCode ^
      description.hashCode ^
      owner.hashCode ^
      pic.hashCode ^
      duration.hashCode ^
      stats.hashCode ^
      cid.hashCode ^
      pages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoInfo &&
          runtimeType == other.runtimeType &&
          bvid == other.bvid &&
          aid == other.aid &&
          title == other.title &&
          description == other.description &&
          owner == other.owner &&
          pic == other.pic &&
          duration == other.duration &&
          stats == other.stats &&
          cid == other.cid &&
          pages == other.pages;
}

class VideoOwner {
  final PlatformInt64 mid;
  final String name;
  final Image face;

  const VideoOwner({
    required this.mid,
    required this.name,
    required this.face,
  });

  @override
  int get hashCode => mid.hashCode ^ name.hashCode ^ face.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoOwner &&
          runtimeType == other.runtimeType &&
          mid == other.mid &&
          name == other.name &&
          face == other.face;
}

class VideoPage {
  final PlatformInt64 cid;
  final int page;
  final String part_;
  final int duration;

  const VideoPage({
    required this.cid,
    required this.page,
    required this.part_,
    required this.duration,
  });

  @override
  int get hashCode =>
      cid.hashCode ^ page.hashCode ^ part_.hashCode ^ duration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoPage &&
          runtimeType == other.runtimeType &&
          cid == other.cid &&
          page == other.page &&
          part_ == other.part_ &&
          duration == other.duration;
}

enum VideoQuality {
  low,
  medium,
  high,
  ultra,
  fourK,
}

class VideoSegment {
  final String url;
  final BigInt size;
  final int duration;

  const VideoSegment({
    required this.url,
    required this.size,
    required this.duration,
  });

  @override
  int get hashCode => url.hashCode ^ size.hashCode ^ duration.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoSegment &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          size == other.size &&
          duration == other.duration;
}

class VideoStats {
  final BigInt viewCount;
  final BigInt likeCount;
  final BigInt coinCount;
  final BigInt collectCount;

  const VideoStats({
    required this.viewCount,
    required this.likeCount,
    required this.coinCount,
    required this.collectCount,
  });

  @override
  int get hashCode =>
      viewCount.hashCode ^
      likeCount.hashCode ^
      coinCount.hashCode ^
      collectCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoStats &&
          runtimeType == other.runtimeType &&
          viewCount == other.viewCount &&
          likeCount == other.likeCount &&
          coinCount == other.coinCount &&
          collectCount == other.collectCount;
}

class VideoUrl {
  final VideoQuality quality;
  final VideoFormat format;
  final List<VideoSegment> segments;

  const VideoUrl({
    required this.quality,
    required this.format,
    required this.segments,
  });

  @override
  int get hashCode => quality.hashCode ^ format.hashCode ^ segments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoUrl &&
          runtimeType == other.runtimeType &&
          quality == other.quality &&
          format == other.format &&
          segments == other.segments;
}
