// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SerializableError implements FrbException {
  final String code;
  final String message;

  const SerializableError({
    required this.code,
    required this.message,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SerializableError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;

  @override
  String toString() => 'SerializableError($code: $message)';
}
