// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'package:PiliPlus/src/rust/api/bridge.dart';
import 'package:PiliPlus/src/rust/api/rcmd.dart';
import 'package:PiliPlus/src/rust/api/simple.dart';
import 'package:PiliPlus/src/rust/api/video.dart';
import 'package:PiliPlus/src/rust/api/wbi.dart';
import 'dart:async';
import 'dart:convert';
import 'package:PiliPlus/src/rust/error.dart';
import 'package:PiliPlus/src/rust/error/api_error.dart';
import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:PiliPlus/src/rust/models/common.dart';
import 'package:PiliPlus/src/rust/models/rcmd.dart';
import 'package:PiliPlus/src/rust/models/video.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1534169933;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'pilicore',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiWbiEncWbi({
    required HashMapStringString params,
    required String mixinKey,
  });

  Future<List<RcmdVideoInfo>> crateApiRcmdGetRecommendList({
    required int ps,
    required int freshIdx,
  });

  String crateApiBridgeGetVersion();

  Future<VideoInfo> crateApiVideoGetVideoInfo({required String bvid});

  Future<VideoUrl> crateApiVideoGetVideoUrl({
    required String bvid,
    required PlatformInt64 cid,
    required VideoQuality quality,
  });

  Future<(String, String, String)> crateApiWbiGetWbiKeysCached();

  String crateApiSimpleGreet({required String name});

  bool crateApiBridgeHealthCheck();

  Future<void> crateApiSimpleInitApp();

  void crateApiBridgeInitCore();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApiError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApiError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ApiErrorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_BoxError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_BoxError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_BoxErrorPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HashMapStringString;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HashMapStringString;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_HashMapStringStringPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiWbiEncWbi({
    required HashMapStringString params,
    required String mixinKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapStringString(
            params,
            serializer,
          );
          sse_encode_String(mixinKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWbiEncWbiConstMeta,
        argValues: [params, mixinKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWbiEncWbiConstMeta => const TaskConstMeta(
    debugName: "enc_wbi",
    argNames: ["params", "mixinKey"],
  );

  @override
  Future<List<RcmdVideoInfo>> crateApiRcmdGetRecommendList({
    required int ps,
    required int freshIdx,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(ps, serializer);
          sse_encode_i_32(freshIdx, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rcmd_video_info,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError,
        ),
        constMeta: kCrateApiRcmdGetRecommendListConstMeta,
        argValues: [ps, freshIdx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRcmdGetRecommendListConstMeta =>
      const TaskConstMeta(
        debugName: "get_recommend_list",
        argNames: ["ps", "freshIdx"],
      );

  @override
  String crateApiBridgeGetVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeGetVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeGetVersionConstMeta => const TaskConstMeta(
    debugName: "get_version",
    argNames: [],
  );

  @override
  Future<VideoInfo> crateApiVideoGetVideoInfo({required String bvid}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bvid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_info,
          decodeErrorData: sse_decode_serializable_error,
        ),
        constMeta: kCrateApiVideoGetVideoInfoConstMeta,
        argValues: [bvid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoGetVideoInfoConstMeta => const TaskConstMeta(
    debugName: "get_video_info",
    argNames: ["bvid"],
  );

  @override
  Future<VideoUrl> crateApiVideoGetVideoUrl({
    required String bvid,
    required PlatformInt64 cid,
    required VideoQuality quality,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bvid, serializer);
          sse_encode_i_64(cid, serializer);
          sse_encode_video_quality(quality, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_video_url,
          decodeErrorData: sse_decode_serializable_error,
        ),
        constMeta: kCrateApiVideoGetVideoUrlConstMeta,
        argValues: [bvid, cid, quality],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVideoGetVideoUrlConstMeta => const TaskConstMeta(
    debugName: "get_video_url",
    argNames: ["bvid", "cid", "quality"],
  );

  @override
  Future<(String, String, String)> crateApiWbiGetWbiKeysCached() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_string_string_string,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError,
        ),
        constMeta: kCrateApiWbiGetWbiKeysCachedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWbiGetWbiKeysCachedConstMeta =>
      const TaskConstMeta(
        debugName: "get_wbi_keys_cached",
        argNames: [],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
    debugName: "greet",
    argNames: ["name"],
  );

  @override
  bool crateApiBridgeHealthCheck() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeHealthCheckConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeHealthCheckConstMeta => const TaskConstMeta(
    debugName: "health_check",
    argNames: [],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
    debugName: "init_app",
    argNames: [],
  );

  @override
  void crateApiBridgeInitCore() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBridgeInitCoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBridgeInitCoreConstMeta => const TaskConstMeta(
    debugName: "init_core",
    argNames: [],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ApiError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ApiError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_BoxError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_BoxError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_HashMapStringString => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapStringString;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_HashMapStringString => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapStringString;

  @protected
  ApiError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BoxError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BoxErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HashMapStringString
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapStringString(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HashMapStringStringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ApiError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BoxError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BoxErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  HashMapStringString
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapStringString(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return HashMapStringStringImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Image dco_decode_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Image(
      url: dco_decode_String(arr[0]),
      width: dco_decode_opt_box_autoadd_u_32(arr[1]),
      height: dco_decode_opt_box_autoadd_u_32(arr[2]),
    );
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RcmdVideoInfo> dco_decode_list_rcmd_video_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rcmd_video_info).toList();
  }

  @protected
  List<VideoPage> dco_decode_list_video_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_video_page).toList();
  }

  @protected
  List<VideoSegment> dco_decode_list_video_segment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_video_segment).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  RcmdOwner dco_decode_rcmd_owner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RcmdOwner(
      mid: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      face: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  RcmdStat dco_decode_rcmd_stat(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RcmdStat(
      view: dco_decode_opt_box_autoadd_i_64(arr[0]),
      like: dco_decode_opt_box_autoadd_i_64(arr[1]),
      danmaku: dco_decode_opt_box_autoadd_i_64(arr[2]),
    );
  }

  @protected
  RcmdVideoInfo dco_decode_rcmd_video_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return RcmdVideoInfo(
      id: dco_decode_opt_box_autoadd_i_64(arr[0]),
      bvid: dco_decode_String(arr[1]),
      cid: dco_decode_opt_box_autoadd_i_64(arr[2]),
      goto: dco_decode_opt_String(arr[3]),
      uri: dco_decode_opt_String(arr[4]),
      pic: dco_decode_opt_String(arr[5]),
      title: dco_decode_String(arr[6]),
      duration: dco_decode_i_32(arr[7]),
      pubdate: dco_decode_opt_box_autoadd_i_64(arr[8]),
      owner: dco_decode_rcmd_owner(arr[9]),
      stat: dco_decode_rcmd_stat(arr[10]),
      isFollowed: dco_decode_bool(arr[11]),
      rcmdReason: dco_decode_opt_String(arr[12]),
    );
  }

  @protected
  (String, String, String) dco_decode_record_string_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) {
      throw Exception('Expected 3 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
      dco_decode_String(arr[2]),
    );
  }

  @protected
  SerializableError dco_decode_serializable_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SerializableError(
      code: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VideoFormat dco_decode_video_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoFormat.values[raw as int];
  }

  @protected
  VideoInfo dco_decode_video_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return VideoInfo(
      bvid: dco_decode_String(arr[0]),
      aid: dco_decode_i_64(arr[1]),
      title: dco_decode_String(arr[2]),
      description: dco_decode_String(arr[3]),
      owner: dco_decode_video_owner(arr[4]),
      pic: dco_decode_image(arr[5]),
      duration: dco_decode_u_32(arr[6]),
      stats: dco_decode_video_stats(arr[7]),
      cid: dco_decode_i_64(arr[8]),
      pages: dco_decode_list_video_page(arr[9]),
    );
  }

  @protected
  VideoOwner dco_decode_video_owner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VideoOwner(
      mid: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      face: dco_decode_image(arr[2]),
    );
  }

  @protected
  VideoPage dco_decode_video_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VideoPage(
      cid: dco_decode_i_64(arr[0]),
      page: dco_decode_i_32(arr[1]),
      part_: dco_decode_String(arr[2]),
      duration: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  VideoQuality dco_decode_video_quality(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoQuality.values[raw as int];
  }

  @protected
  VideoSegment dco_decode_video_segment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VideoSegment(
      url: dco_decode_String(arr[0]),
      size: dco_decode_u_64(arr[1]),
      duration: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  VideoStats dco_decode_video_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VideoStats(
      viewCount: dco_decode_u_64(arr[0]),
      likeCount: dco_decode_u_64(arr[1]),
      coinCount: dco_decode_u_64(arr[2]),
      collectCount: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  VideoUrl dco_decode_video_url(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VideoUrl(
      quality: dco_decode_video_quality(arr[0]),
      format: dco_decode_video_format(arr[1]),
      segments: dco_decode_list_video_segment(arr[2]),
    );
  }

  @protected
  ApiError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BoxError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BoxErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HashMapStringString
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapStringString(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HashMapStringStringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ApiError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BoxError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BoxErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  HashMapStringString
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapStringString(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return HashMapStringStringImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Image sse_decode_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    return Image(url: var_url, width: var_width, height: var_height);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RcmdVideoInfo> sse_decode_list_rcmd_video_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RcmdVideoInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rcmd_video_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<VideoPage> sse_decode_list_video_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VideoPage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_video_page(deserializer));
    }
    return ans_;
  }

  @protected
  List<VideoSegment> sse_decode_list_video_segment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VideoSegment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_video_segment(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RcmdOwner sse_decode_rcmd_owner(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mid = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_face = sse_decode_opt_String(deserializer);
    return RcmdOwner(mid: var_mid, name: var_name, face: var_face);
  }

  @protected
  RcmdStat sse_decode_rcmd_stat(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_view = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_like = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_danmaku = sse_decode_opt_box_autoadd_i_64(deserializer);
    return RcmdStat(view: var_view, like: var_like, danmaku: var_danmaku);
  }

  @protected
  RcmdVideoInfo sse_decode_rcmd_video_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_bvid = sse_decode_String(deserializer);
    var var_cid = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_goto = sse_decode_opt_String(deserializer);
    var var_uri = sse_decode_opt_String(deserializer);
    var var_pic = sse_decode_opt_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_duration = sse_decode_i_32(deserializer);
    var var_pubdate = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_owner = sse_decode_rcmd_owner(deserializer);
    var var_stat = sse_decode_rcmd_stat(deserializer);
    var var_isFollowed = sse_decode_bool(deserializer);
    var var_rcmdReason = sse_decode_opt_String(deserializer);
    return RcmdVideoInfo(
      id: var_id,
      bvid: var_bvid,
      cid: var_cid,
      goto: var_goto,
      uri: var_uri,
      pic: var_pic,
      title: var_title,
      duration: var_duration,
      pubdate: var_pubdate,
      owner: var_owner,
      stat: var_stat,
      isFollowed: var_isFollowed,
      rcmdReason: var_rcmdReason,
    );
  }

  @protected
  (String, String, String) sse_decode_record_string_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    var var_field2 = sse_decode_String(deserializer);
    return (var_field0, var_field1, var_field2);
  }

  @protected
  SerializableError sse_decode_serializable_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return SerializableError(code: var_code, message: var_message);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VideoFormat sse_decode_video_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return VideoFormat.values[inner];
  }

  @protected
  VideoInfo sse_decode_video_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bvid = sse_decode_String(deserializer);
    var var_aid = sse_decode_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_owner = sse_decode_video_owner(deserializer);
    var var_pic = sse_decode_image(deserializer);
    var var_duration = sse_decode_u_32(deserializer);
    var var_stats = sse_decode_video_stats(deserializer);
    var var_cid = sse_decode_i_64(deserializer);
    var var_pages = sse_decode_list_video_page(deserializer);
    return VideoInfo(
      bvid: var_bvid,
      aid: var_aid,
      title: var_title,
      description: var_description,
      owner: var_owner,
      pic: var_pic,
      duration: var_duration,
      stats: var_stats,
      cid: var_cid,
      pages: var_pages,
    );
  }

  @protected
  VideoOwner sse_decode_video_owner(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mid = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_face = sse_decode_image(deserializer);
    return VideoOwner(mid: var_mid, name: var_name, face: var_face);
  }

  @protected
  VideoPage sse_decode_video_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cid = sse_decode_i_64(deserializer);
    var var_page = sse_decode_i_32(deserializer);
    var var_part_ = sse_decode_String(deserializer);
    var var_duration = sse_decode_u_32(deserializer);
    return VideoPage(
      cid: var_cid,
      page: var_page,
      part_: var_part_,
      duration: var_duration,
    );
  }

  @protected
  VideoQuality sse_decode_video_quality(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return VideoQuality.values[inner];
  }

  @protected
  VideoSegment sse_decode_video_segment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_duration = sse_decode_u_32(deserializer);
    return VideoSegment(url: var_url, size: var_size, duration: var_duration);
  }

  @protected
  VideoStats sse_decode_video_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_viewCount = sse_decode_u_64(deserializer);
    var var_likeCount = sse_decode_u_64(deserializer);
    var var_coinCount = sse_decode_u_64(deserializer);
    var var_collectCount = sse_decode_u_64(deserializer);
    return VideoStats(
      viewCount: var_viewCount,
      likeCount: var_likeCount,
      coinCount: var_coinCount,
      collectCount: var_collectCount,
    );
  }

  @protected
  VideoUrl sse_decode_video_url(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_quality = sse_decode_video_quality(deserializer);
    var var_format = sse_decode_video_format(deserializer);
    var var_segments = sse_decode_list_video_segment(deserializer);
    return VideoUrl(
      quality: var_quality,
      format: var_format,
      segments: var_segments,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    ApiError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError(
    BoxError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BoxErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapStringString(
    HashMapStringString self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HashMapStringStringImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiError(
    ApiError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxError(
    BoxError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BoxErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerHashMapStringString(
    HashMapStringString self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as HashMapStringStringImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_image(Image self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rcmd_video_info(
    List<RcmdVideoInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rcmd_video_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_video_page(
    List<VideoPage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_video_page(item, serializer);
    }
  }

  @protected
  void sse_encode_list_video_segment(
    List<VideoSegment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_video_segment(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_rcmd_owner(RcmdOwner self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.mid, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.face, serializer);
  }

  @protected
  void sse_encode_rcmd_stat(RcmdStat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.view, serializer);
    sse_encode_opt_box_autoadd_i_64(self.like, serializer);
    sse_encode_opt_box_autoadd_i_64(self.danmaku, serializer);
  }

  @protected
  void sse_encode_rcmd_video_info(
    RcmdVideoInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.id, serializer);
    sse_encode_String(self.bvid, serializer);
    sse_encode_opt_box_autoadd_i_64(self.cid, serializer);
    sse_encode_opt_String(self.goto, serializer);
    sse_encode_opt_String(self.uri, serializer);
    sse_encode_opt_String(self.pic, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_32(self.duration, serializer);
    sse_encode_opt_box_autoadd_i_64(self.pubdate, serializer);
    sse_encode_rcmd_owner(self.owner, serializer);
    sse_encode_rcmd_stat(self.stat, serializer);
    sse_encode_bool(self.isFollowed, serializer);
    sse_encode_opt_String(self.rcmdReason, serializer);
  }

  @protected
  void sse_encode_record_string_string_string(
    (String, String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
    sse_encode_String(self.$3, serializer);
  }

  @protected
  void sse_encode_serializable_error(
    SerializableError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_video_format(VideoFormat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_video_info(VideoInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.bvid, serializer);
    sse_encode_i_64(self.aid, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_video_owner(self.owner, serializer);
    sse_encode_image(self.pic, serializer);
    sse_encode_u_32(self.duration, serializer);
    sse_encode_video_stats(self.stats, serializer);
    sse_encode_i_64(self.cid, serializer);
    sse_encode_list_video_page(self.pages, serializer);
  }

  @protected
  void sse_encode_video_owner(VideoOwner self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.mid, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_image(self.face, serializer);
  }

  @protected
  void sse_encode_video_page(VideoPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.cid, serializer);
    sse_encode_i_32(self.page, serializer);
    sse_encode_String(self.part_, serializer);
    sse_encode_u_32(self.duration, serializer);
  }

  @protected
  void sse_encode_video_quality(VideoQuality self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_video_segment(VideoSegment self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_u_32(self.duration, serializer);
  }

  @protected
  void sse_encode_video_stats(VideoStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.viewCount, serializer);
    sse_encode_u_64(self.likeCount, serializer);
    sse_encode_u_64(self.coinCount, serializer);
    sse_encode_u_64(self.collectCount, serializer);
  }

  @protected
  void sse_encode_video_url(VideoUrl self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_video_quality(self.quality, serializer);
    sse_encode_video_format(self.format, serializer);
    sse_encode_list_video_segment(self.segments, serializer);
  }
}

@sealed
class ApiErrorImpl extends RustOpaque implements ApiError {
  // Not to be used by end users
  ApiErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ApiErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ApiError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiErrorPtr,
  );
}

@sealed
class BoxErrorImpl extends RustOpaque implements BoxError {
  // Not to be used by end users
  BoxErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  BoxErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_BoxError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_BoxError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_BoxErrorPtr,
  );
}

@sealed
class HashMapStringStringImpl extends RustOpaque
    implements HashMapStringString {
  // Not to be used by end users
  HashMapStringStringImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  HashMapStringStringImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_HashMapStringString,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_HashMapStringString,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_HashMapStringStringPtr,
  );
}
