// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'task.freezed.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DownloadTask>>
abstract class DownloadTask implements RustOpaqueInterface {}

class DownloadEvent {
  final String taskId;
  final DownloadEventType eventType;

  const DownloadEvent({
    required this.taskId,
    required this.eventType,
  });

  @override
  int get hashCode => taskId.hashCode ^ eventType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadEvent &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          eventType == other.eventType;
}

@freezed
sealed class DownloadEventType with _$DownloadEventType {
  const DownloadEventType._();

  const factory DownloadEventType.progress({
    required BigInt downloaded,
    required BigInt total,
    required double speed,
  }) = DownloadEventType_Progress;
  const factory DownloadEventType.paused() = DownloadEventType_Paused;
  const factory DownloadEventType.completed() = DownloadEventType_Completed;
  const factory DownloadEventType.failed({
    required String error,
  }) = DownloadEventType_Failed;
  const factory DownloadEventType.cancelled() = DownloadEventType_Cancelled;
}
