// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/models/account.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get current logged-in account
Future<Account?> getCurrentAccount() =>
    RustLib.instance.api.crateApiAccountGetCurrentAccount();

/// Switch to a different account
Future<void> switchAccount({required String accountId}) =>
    RustLib.instance.api.crateApiAccountSwitchAccount(accountId: accountId);

/// Get all saved accounts
Future<List<Account>> getAllAccounts() =>
    RustLib.instance.api.crateApiAccountGetAllAccounts();

/// Save an account
Future<void> saveAccount({required Account account}) =>
    RustLib.instance.api.crateApiAccountSaveAccount(account: account);

/// Delete an account
Future<void> deleteAccount({required String accountId}) =>
    RustLib.instance.api.crateApiAccountDeleteAccount(accountId: accountId);

/// Get current account ID
Future<String?> getCurrentAccountId() =>
    RustLib.instance.api.crateApiAccountGetCurrentAccountId();
