// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/error.dart';
import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/models/account.dart';
import 'package:PiliPlus/src/rust/models/comments.dart';
import 'package:PiliPlus/src/rust/models/common.dart';
import 'package:PiliPlus/src/rust/models/live.dart';
import 'package:PiliPlus/src/rust/models/rcmd.dart';
import 'package:PiliPlus/src/rust/models/search.dart';
import 'package:PiliPlus/src/rust/models/user.dart';
import 'package:PiliPlus/src/rust/models/video.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the Rust core
void initCore() => RustLib.instance.api.crateApiBridgeInitCore();

/// Get version information
String getVersion() => RustLib.instance.api.crateApiBridgeGetVersion();

/// Health check
bool healthCheck() => RustLib.instance.api.crateApiBridgeHealthCheck();

/// Expose VideoInfo type to bridge
Future<VideoInfo> exposeVideoInfoType() =>
    RustLib.instance.api.crateApiBridgeExposeVideoInfoType();

/// Expose VideoUrl type to bridge
Future<VideoUrl> exposeVideoUrlType() =>
    RustLib.instance.api.crateApiBridgeExposeVideoUrlType();

/// Expose VideoOwner type to bridge
Future<VideoOwner> exposeVideoOwnerType() =>
    RustLib.instance.api.crateApiBridgeExposeVideoOwnerType();

/// Expose VideoStats type to bridge
Future<VideoStats> exposeVideoStatsType() =>
    RustLib.instance.api.crateApiBridgeExposeVideoStatsType();

/// Expose VideoPage type to bridge
Future<VideoPage> exposeVideoPageType() =>
    RustLib.instance.api.crateApiBridgeExposeVideoPageType();

/// Expose VideoSegment type to bridge
Future<VideoSegment> exposeVideoSegmentType() =>
    RustLib.instance.api.crateApiBridgeExposeVideoSegmentType();

/// Expose Image type to bridge
Future<Image> exposeImageType() =>
    RustLib.instance.api.crateApiBridgeExposeImageType();

/// Expose Account type to bridge
Future<Account> exposeAccountType() =>
    RustLib.instance.api.crateApiBridgeExposeAccountType();

/// Expose DynamicsList type to bridge
Future<DynamicsList> exposeDynamicsListType() =>
    RustLib.instance.api.crateApiBridgeExposeDynamicsListType();

/// Expose DynamicsItem type to bridge
Future<DynamicsItem> exposeDynamicsItemType() =>
    RustLib.instance.api.crateApiBridgeExposeDynamicsItemType();

/// Expose LiveRoomInfo type to bridge
Future<LiveRoomInfo> exposeLiveRoomInfoType() =>
    RustLib.instance.api.crateApiBridgeExposeLiveRoomInfoType();

/// Expose LivePlayUrl type to bridge
Future<LivePlayUrl> exposeLivePlayUrlType() =>
    RustLib.instance.api.crateApiBridgeExposeLivePlayUrlType();

/// Expose CommentList type to bridge
Future<CommentList> exposeCommentListType() =>
    RustLib.instance.api.crateApiBridgeExposeCommentListType();

/// Expose SearchResults type to bridge
Future<SearchResults> exposeSearchResultsType() =>
    RustLib.instance.api.crateApiBridgeExposeSearchResultsType();

/// Expose SearchResult type to bridge
Future<SearchResult> exposeSearchResultType() =>
    RustLib.instance.api.crateApiBridgeExposeSearchResultType();

Future<List<RcmdVideoInfo>> getRecommendList({
  required int ps,
  required int freshIdx,
}) => RustLib.instance.api.crateApiBridgeGetRecommendList(
  ps: ps,
  freshIdx: freshIdx,
);

Future<List<RcmdVideoInfo>> getRecommendListApp({
  required int ps,
  required int freshIdx,
}) => RustLib.instance.api.crateApiBridgeGetRecommendListApp(
  ps: ps,
  freshIdx: freshIdx,
);

Future<UserInfo> getUserInfo() =>
    RustLib.instance.api.crateApiBridgeGetUserInfo();

Future<UserStats> getUserStats() =>
    RustLib.instance.api.crateApiBridgeGetUserStats();

Future<SearchVideoResult> searchVideos({
  required String keyword,
  required int page,
  String? order,
  int? duration,
  int? tids,
}) => RustLib.instance.api.crateApiBridgeSearchVideos(
  keyword: keyword,
  page: page,
  order: order,
  duration: duration,
  tids: tids,
);
