// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/models/common.dart';
import 'package:PiliPlus/src/rust/models/rcmd.dart';
import 'package:PiliPlus/src/rust/models/video.dart';
import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the Rust core
void initCore() => RustLib.instance.api.pilicoreApiBridgeInitCore();

/// Get version information
String getVersion() => RustLib.instance.api.pilicoreApiBridgeGetVersion();

/// Health check
bool healthCheck() => RustLib.instance.api.pilicoreApiBridgeHealthCheck();

/// Get recommendation list from Bilibili API
Future<List<RcmdVideoInfo>> getRecommendList({
  required int ps,
  required int freshIdx,
}) =>
    RustLib.instance.api.pilicoreApiBridgeGetRecommendList(
      ps: ps,
      freshIdx: freshIdx,
    );
