// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the Rust core
void initCore() => RustLib.instance.api.crateApiBridgeInitCore();

/// Get version information
String getVersion() => RustLib.instance.api.crateApiBridgeGetVersion();

/// Health check
bool healthCheck() => RustLib.instance.api.crateApiBridgeHealthCheck();
