// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/error.dart';
import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get video comments
Future<ApiResult> getVideoComments({
  required PlatformInt64 oid,
  required int page,
  required int pageSize,
}) => RustLib.instance.api.crateApiCommentsGetVideoComments(
  oid: oid,
  page: page,
  pageSize: pageSize,
);
