// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/error/api_error.dart';
import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/models/download.dart';
import 'package:PiliPlus/src/rust/models/video.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_task_to_bridge`, `get_manager`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DownloadManager`

/// Initialize the download manager with a download directory
Future<void> initDownloadManager({required String downloadDir}) => RustLib
    .instance
    .api
    .crateApiDownloadInitDownloadManager(downloadDir: downloadDir);

/// Create a new download task
Future<DownloadTaskData> createDownloadTask({
  required String videoId,
  required String title,
  required VideoQuality quality,
}) => RustLib.instance.api.crateApiDownloadCreateDownloadTask(
  videoId: videoId,
  title: title,
  quality: quality,
);

/// Start downloading a task
Future<void> startDownload({required String taskId}) =>
    RustLib.instance.api.crateApiDownloadStartDownload(taskId: taskId);

/// Pause an in-progress download
Future<void> pauseDownload({required String taskId}) =>
    RustLib.instance.api.crateApiDownloadPauseDownload(taskId: taskId);

/// Resume a paused download
Future<void> resumeDownload({required String taskId}) =>
    RustLib.instance.api.crateApiDownloadResumeDownload(taskId: taskId);

/// Cancel a download
Future<void> cancelDownload({required String taskId}) =>
    RustLib.instance.api.crateApiDownloadCancelDownload(taskId: taskId);

/// Get a specific download task
Future<DownloadTaskData?> getDownloadTask({required String taskId}) =>
    RustLib.instance.api.crateApiDownloadGetDownloadTask(taskId: taskId);

/// List all download tasks
Future<List<DownloadTaskData>> listDownloadTasks() =>
    RustLib.instance.api.crateApiDownloadListDownloadTasks();
