// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/error.dart';
import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/models/common.dart';
import 'package:PiliPlus/src/rust/models/video.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get user dynamics/posts from Bilibili API
Future<DynamicsList> getUserDynamics({
  required PlatformInt64 uid,
  String? offset,
}) => RustLib.instance.api.crateApiDynamicsGetUserDynamics(
  uid: uid,
  offset: offset,
);

/// Get dynamics detail by ID from Bilibili API
Future<DynamicsItem> getDynamicsDetail({required String dynamicId}) => RustLib
    .instance
    .api
    .crateApiDynamicsGetDynamicsDetail(dynamicId: dynamicId);
