// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/error.dart';
import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/models/rcmd.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get recommendation list from Bilibili APP API
///
/// Fetches the recommendation feed from Bilibili's APP interface
/// and filters for video content (card_goto='av')
///
/// # Parameters
/// * `ps` - Page size (number of recommendations to fetch)
/// * `fresh_idx` - Freshness index for recommendations (idx parameter)
///
/// # Returns
/// Result containing vector of RcmdVideoInfo structs
///
/// # Errors
/// Returns SerializableError for:
/// - HTTP request failures
/// - JSON parsing failures
/// - API error responses
/// - Network issues
///
/// # Examples
/// ```rust
/// let recommendations = get_recommend_list_app(10, 0).await?;
/// ```
Future<List<RcmdVideoInfo>> getRecommendListApp({
  required int ps,
  required int freshIdx,
}) => RustLib.instance.api.crateApiRcmdAppGetRecommendListApp(
  ps: ps,
  freshIdx: freshIdx,
);
