// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/error.dart';
import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/models/search.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_query_string`

/// Search for videos on Bilibili
Future<SearchVideoResult> searchVideos({
  required String keyword,
  required int page,
  String? order,
  int? duration,
  int? tids,
}) => RustLib.instance.api.crateApiSearchSearchVideos(
  keyword: keyword,
  page: page,
  order: order,
  duration: duration,
  tids: tids,
);
