// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/error.dart';
import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/models/common.dart';
import 'package:PiliPlus/src/rust/models/user.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get current user information (uses auth cookie from HTTP client)
Future<UserInfo> getUserInfo() =>
    RustLib.instance.api.crateApiUserGetUserInfo();

/// Get current user statistics (uses auth cookie from HTTP client)
Future<UserStats> getUserStats() =>
    RustLib.instance.api.crateApiUserGetUserStats();
