// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/error.dart';
import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:PiliPlus/src/rust/models/common.dart';
import 'package:PiliPlus/src/rust/models/video.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get video information from Bilibili API
Future<VideoInfo> getVideoInfo({required String bvid}) =>
    RustLib.instance.api.crateApiVideoGetVideoInfo(bvid: bvid);

/// Get video playback URL from Bilibili API
Future<VideoUrl> getVideoUrl({
  required String bvid,
  required PlatformInt64 cid,
  required VideoQuality quality,
}) => RustLib.instance.api.crateApiVideoGetVideoUrl(
  bvid: bvid,
  cid: cid,
  quality: quality,
);
