// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:PiliPlus/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_filename`, `get_mixin_key`, `get_wbi_keys`, `is_expired`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UserData`, `UserInfoResponse`, `WbiCache`, `WbiImg`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Get WBI keys with caching
///
/// Returns cached WBI keys if available and not expired,
/// otherwise fetches new keys from API
///
/// # Returns
/// Result containing tuple of (img_url, sub_url, mixin_key)
///
/// # Errors
/// Returns reqwest::Error for HTTP failures
/// Returns json::Error for JSON parsing failures
///
/// # Examples
/// ```rust
/// let (img_url, sub_url, mixin_key) = get_wbi_keys_cached().await?;
/// ```
Future<(String, String, String)> getWbiKeysCached() =>
    RustLib.instance.api.crateApiWbiGetWbiKeysCached();

/// Encode parameters with WBI (Web Bilibili Interface) signing
///
/// Adds timestamp and signature to parameters for API requests
///
/// # Parameters
/// * `params` - Mutable reference to parameters HashMap to be modified
/// * `mixin_key` - The mixin key used for signing
///
/// # Algorithm
/// 1. Add current timestamp as "wts" parameter
/// 2. Sort parameters by key
/// 3. Build query string with URL encoding
/// 4. Filter special characters using ALLOWED_SPECIAL_CHARS
/// 5. Calculate MD5 hash of query + mixin_key
/// 6. Add hash as "w_rid" parameter
///
/// # Examples
/// ```rust
/// let mut params = HashMap::new();
/// params.insert("test".to_string(), "value".to_string());
/// enc_wbi(&mut params, "mixin_key");
/// assert!(params.contains_key("wts"));
/// assert!(params.contains_key("w_rid"));
/// ```
Future<void> encWbi({
  required HashMapStringString params,
  required String mixinKey,
}) =>
    RustLib.instance.api.crateApiWbiEncWbi(params: params, mixinKey: mixinKey);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < Error >>>
abstract class BoxError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HashMap < String , String >>>
abstract class HashMapStringString implements RustOpaqueInterface {}
